services:
  # バックエンドAPI (FastAPIアプリケーション)
  - type: web
    name: syncfam-api
    env: docker
    dockerfilePath: backend/Dockerfile
    dockerContext: backend
    region: singapore
    plan: free
    branch: main
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: syncfam-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "1440"
      - key: DEBUG
        value: "false"
      - key: BACKEND_CORS_ORIGINS
        value: '["https://syncfam.vercel.app"]'
      - key: SETUP_DEMO
        value: "true"
    healthCheckPath: /
    autoDeploy: true

  # PostgreSQLデータベース
  - type: postgres
    name: syncfam-db
    region: singapore
    plan: free
    postgresMajorVersion: 15
    ipAllowList: []
